package flags

import (
	"bytes"
	"encoding/json"
	"strings"
	"testing"
)

func TestListBuiltinTemplates(t *testing.T) {
	got := ListBuiltinTemplates()
	want := []string{
		DocTemplateHTMLDefault,
		DocTemplateHTMLStyled,
		DocTemplateManDefault,
		DocTemplateMarkdownCode,
		DocTemplateMarkdownList,
		DocTemplateMarkdownTable,
	}

	if len(got) != len(want) {
		t.Fatalf("unexpected template count: got %d, want %d", len(got), len(want))
	}

	for i := range want {
		if got[i] != want[i] {
			t.Fatalf("unexpected template at %d: got %q, want %q", i, got[i], want[i])
		}
	}
}

func TestWriteBuiltinTemplate(t *testing.T) {
	var out bytes.Buffer

	if err := WriteBuiltinTemplate(&out, DocTemplateMarkdownList); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if !strings.Contains(out.String(), `doc.tmpl.markdown.section.options`) {
		t.Fatalf("expected markdown template content, got: %q", out.String())
	}

	if err := WriteBuiltinTemplate(&out, "unknown/template"); err == nil {
		t.Fatalf("expected error for unknown template")
	}
}

func TestWriteDocMarkdownBuiltin(t *testing.T) {
	var opts struct {
		Verbose bool `short:"v" long:"verbose" description:"Enable verbose output"`
		Run     struct {
			Force bool `long:"force" description:"Force execution"`
		} `command:"run" description:"Run command"`
	}

	p := NewNamedParser("doc-app", None)
	p.ShortDescription = "Doc app"
	p.LongDescription = "Long description"

	if _, err := p.AddGroup("Application Options", "", &opts); err != nil {
		t.Fatalf("unexpected add group error: %v", err)
	}

	var out bytes.Buffer
	if err := p.WriteDoc(&out, DocFormatMarkdown); err != nil {
		t.Fatalf("unexpected write doc error: %v", err)
	}

	got := out.String()
	for _, needle := range []string{
		"# doc-app",
		"## OPTIONS",
		defaultLongOptDelimiter + "verbose",
		"## COMMANDS",
		"### run",
		defaultLongOptDelimiter + "force",
	} {
		if !strings.Contains(got, needle) {
			t.Fatalf("expected %q in markdown output, got:\n%s", needle, got)
		}
	}
}

func TestWriteDocBuiltinTemplatesIncludeGeneratedMarker(t *testing.T) {
	p := NewNamedParser("generated-marker", None)

	tests := []struct {
		name     string
		format   DocFormat
		template string
		want     []string
	}{
		{
			name:     "markdown-list",
			format:   DocFormatMarkdown,
			template: DocTemplateMarkdownList,
			want:     []string{"<!-- Generated by github.com/woozymasta/flags; do not edit this file directly. -->"},
		},
		{
			name:     "markdown-table",
			format:   DocFormatMarkdown,
			template: DocTemplateMarkdownTable,
			want:     []string{"<!-- Generated by github.com/woozymasta/flags; do not edit this file directly. -->"},
		},
		{
			name:     "markdown-code",
			format:   DocFormatMarkdown,
			template: DocTemplateMarkdownCode,
			want:     []string{"<!-- Generated by github.com/woozymasta/flags; do not edit this file directly. -->"},
		},
		{
			name:     "html-default",
			format:   DocFormatHTML,
			template: DocTemplateHTMLDefault,
			want: []string{
				"<!-- Generated by github.com/woozymasta/flags; do not edit this file directly. -->",
				`<meta name="generator" content="github.com/woozymasta/flags">`,
			},
		},
		{
			name:     "html-styled",
			format:   DocFormatHTML,
			template: DocTemplateHTMLStyled,
			want: []string{
				"<!-- Generated by github.com/woozymasta/flags; do not edit this file directly. -->",
				`<meta name="generator" content="github.com/woozymasta/flags">`,
			},
		},
		{
			name:     "man",
			format:   DocFormatMan,
			template: DocTemplateManDefault,
			want:     []string{`.\" Generated by github.com/woozymasta/flags; do not edit this file directly.`},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var out bytes.Buffer
			if err := p.WriteDoc(&out, tt.format, WithBuiltinTemplate(tt.template)); err != nil {
				t.Fatalf("unexpected write doc error: %v", err)
			}

			got := out.String()
			for _, want := range tt.want {
				if !strings.Contains(got, want) {
					t.Fatalf("expected generated marker %q, got:\n%s", want, got)
				}
			}
		})
	}
}

func TestWriteDocMarkdownBuiltinLocalized(t *testing.T) {
	var opts struct {
		Verbose bool `short:"v" long:"verbose" required:"true" description:"Enable verbose output"`
	}

	p := NewNamedParser("doc-i18n", None)
	p.ShortDescription = "Doc i18n"
	p.LongDescription = "Long description"

	if _, err := p.AddGroup("Application Options", "", &opts); err != nil {
		t.Fatalf("unexpected add group error: %v", err)
	}

	p.SetI18n(I18nConfig{Locale: "ru"})

	var out bytes.Buffer
	if err := p.WriteDoc(&out, DocFormatMarkdown, WithBuiltinTemplate(DocTemplateMarkdownList)); err != nil {
		t.Fatalf("unexpected write doc error: %v", err)
	}

	got := out.String()
	for _, needle := range []string{
		"## ОПЦИИ",
		"Обязательно: `да`",
	} {
		if !strings.Contains(got, needle) {
			t.Fatalf("expected %q in localized markdown output, got:\n%s", needle, got)
		}
	}
}

func TestWriteDocMarkdownListOptionDescriptionsUseContinuationLine(t *testing.T) {
	var opts struct {
		Locale string `short:"l" long:"locale" value-name:"LOCALE" description:"Override language for help, errors, application text, generated documentation, and custom template rendering"`
		Help   bool   `short:"h" long:"help" description:"Show help"`
	}

	p := NewNamedParser("doc-list", None)
	if _, err := p.AddGroup("Application Options", "", &opts); err != nil {
		t.Fatalf("unexpected add group error: %v", err)
	}

	var out bytes.Buffer
	if err := p.WriteDoc(&out, DocFormatMarkdown, WithBuiltinTemplate(DocTemplateMarkdownList)); err != nil {
		t.Fatalf("unexpected write doc error: %v", err)
	}

	got := out.String()
	shortLocale := string(defaultShortOptDelimiter) + "l LOCALE"
	longLocale := string(defaultLongOptDelimiter) + "locale LOCALE"
	shortHelp := string(defaultShortOptDelimiter) + "h"
	longHelp := string(defaultLongOptDelimiter) + "help"
	for _, needle := range []string{
		"* `" + shortLocale + "`, `" + longLocale + "` -\n  Override language for help, errors, application text, generated documentation,\n  and custom template rendering",
		"* `" + shortHelp + "`, `" + longHelp + "` -\n  Show help",
	} {
		if !strings.Contains(got, needle) {
			t.Fatalf("expected %q in markdown list output, got:\n%s", needle, got)
		}
	}

	if strings.Contains(got, "application text\n\n* `"+shortHelp+"`") {
		t.Fatalf("did not expect blank line between option items, got:\n%s", got)
	}

	if strings.Contains(got, "\ndocumentation,\nand custom") {
		t.Fatalf("expected wrapped option description lines to keep list continuation indent, got:\n%s", got)
	}
}

func TestWriteDocMarkdownWrapWidthOption(t *testing.T) {
	var opts struct {
		Value string `long:"value" description:"alpha beta gamma delta epsilon zeta eta theta"`
	}

	p := NewNamedParser("doc-wrap", None)
	if _, err := p.AddGroup("Application Options", "", &opts); err != nil {
		t.Fatalf("unexpected add group error: %v", err)
	}

	var out bytes.Buffer
	if err := p.WriteDoc(
		&out,
		DocFormatMarkdown,
		WithBuiltinTemplate(DocTemplateMarkdownList),
		WithDocRenderStyle(RenderStylePOSIX),
		WithDocWrapWidth(32),
	); err != nil {
		t.Fatalf("unexpected write doc error: %v", err)
	}

	got := out.String()
	want := "* `--value` -\n  alpha beta gamma delta epsilon\n  zeta eta theta"
	if !strings.Contains(got, want) {
		t.Fatalf("expected wrap width to affect markdown list output, got:\n%s", got)
	}
}

func TestWriteDocWrapWidthRejectsNegativeWidth(t *testing.T) {
	p := NewNamedParser("doc-wrap-invalid", None)

	var out bytes.Buffer
	err := p.WriteDoc(&out, DocFormatMarkdown, WithDocWrapWidth(-1))
	if err == nil {
		t.Fatalf("expected negative wrap width error")
	}
	if !strings.Contains(err.Error(), "doc wrap width") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestWriteDocMarkdownUsesLocalizedRootDescription(t *testing.T) {
	p := NewNamedParser("doc-i18n-root", None)
	p.Command.SetLongDescriptionI18nKey("app.description")
	p.SetI18n(I18nConfig{
		Locale: "ru",
		UserCatalog: mapCatalog{
			"ru": {"app.description": "Локализованное описание приложения"},
		},
	})

	var out bytes.Buffer
	if err := p.WriteDoc(&out, DocFormatMarkdown, WithBuiltinTemplate(DocTemplateMarkdownList)); err != nil {
		t.Fatalf("unexpected write doc error: %v", err)
	}

	got := out.String()
	if !strings.Contains(got, "## ОПИСАНИЕ") {
		t.Fatalf("expected localized description section, got:\n%s", got)
	}
	if !strings.Contains(got, "Локализованное описание приложения") {
		t.Fatalf("expected localized root description, got:\n%s", got)
	}
}

func TestWriteDocBuiltinTemplatesSkipEmptyRootSections(t *testing.T) {
	formats := []struct {
		name     string
		format   DocFormat
		template string
		empty    []string
	}{
		{
			name:     "markdown-list",
			format:   DocFormatMarkdown,
			template: DocTemplateMarkdownList,
			empty:    []string{"## DESCRIPTION", "## OPTIONS"},
		},
		{
			name:     "markdown-table",
			format:   DocFormatMarkdown,
			template: DocTemplateMarkdownTable,
			empty:    []string{"## DESCRIPTION", "## OPTIONS"},
		},
		{
			name:     "markdown-code",
			format:   DocFormatMarkdown,
			template: DocTemplateMarkdownCode,
			empty:    []string{"## DESCRIPTION", "## OPTIONS"},
		},
		{
			name:     "man",
			format:   DocFormatMan,
			template: DocTemplateManDefault,
			empty:    []string{".SH DESCRIPTION", ".SH OPTIONS"},
		},
		{
			name:     "html",
			format:   DocFormatHTML,
			template: DocTemplateHTMLDefault,
			empty:    []string{"<h2>Description</h2>", "<h2>Options</h2>"},
		},
		{
			name:     "html-styled",
			format:   DocFormatHTML,
			template: DocTemplateHTMLStyled,
			empty:    []string{"<h2>Description</h2>", "<h2>Options</h2>"},
		},
	}

	for _, tt := range formats {
		t.Run(tt.name, func(t *testing.T) {
			p := NewNamedParser("empty-doc", None)

			var out bytes.Buffer
			if err := p.WriteDoc(&out, tt.format, WithBuiltinTemplate(tt.template)); err != nil {
				t.Fatalf("unexpected write doc error: %v", err)
			}

			got := out.String()
			for _, needle := range tt.empty {
				if strings.Contains(got, needle) {
					t.Fatalf("did not expect empty section %q, got:\n%s", needle, got)
				}
			}
		})
	}
}

func TestWriteDocMarkdownBuiltinTable(t *testing.T) {
	var opts struct {
		Verbose bool `short:"v" long:"verbose" description:"Enable verbose output"`
	}

	p := NewNamedParser("doc-table", None)
	p.ShortDescription = "Doc table"
	p.LongDescription = "Long description"

	if _, err := p.AddGroup("Application Options", "", &opts); err != nil {
		t.Fatalf("unexpected add group error: %v", err)
	}

	var out bytes.Buffer
	if err := p.WriteDoc(&out, DocFormatMarkdown, WithBuiltinTemplate(DocTemplateMarkdownTable)); err != nil {
		t.Fatalf("unexpected write doc error: %v", err)
	}

	got := out.String()
	for _, needle := range []string{
		"|Option|Description|Required|",
		"|---|---|---|",
		defaultLongOptDelimiter + "verbose",
	} {
		if !strings.Contains(got, needle) {
			t.Fatalf("expected %q in markdown output, got:\n%s", needle, got)
		}
	}
}

func TestWriteDocMarkdownBuiltinTableSkipsEmptyColumns(t *testing.T) {
	var opts struct {
		Plain   bool   `long:"plain" description:"Plain option"`
		EnvOnly string `long:"env-only" env:"APP_ENV" description:"Env option"`
		Nested  struct {
			Help bool `long:"help" description:"Help option"`
		} `group:"Nested"`
	}

	p := NewNamedParser("doc-table-columns", None)
	if _, err := p.AddGroup("Application Options", "", &opts); err != nil {
		t.Fatalf("unexpected add group error: %v", err)
	}

	var out bytes.Buffer
	if err := p.WriteDoc(&out, DocFormatMarkdown, WithBuiltinTemplate(DocTemplateMarkdownTable)); err != nil {
		t.Fatalf("unexpected write doc error: %v", err)
	}

	got := out.String()
	if !strings.Contains(got, "|Option|Description|Environment|Required|") {
		t.Fatalf("expected env column without synthetic default, got:\n%s", got)
	}
	if !strings.Contains(got, "|Option|Description|Required|") {
		t.Fatalf("expected compact table for group with empty default/env columns, got:\n%s", got)
	}
}

func TestWriteDocMarkdownBuiltinCode(t *testing.T) {
	var opts struct {
		Verbose bool `short:"v" long:"verbose" description:"Enable verbose output"`
	}

	p := NewNamedParser("doc-code", None)
	p.ShortDescription = "Doc code"
	p.LongDescription = "Long description"

	if _, err := p.AddGroup("Application Options", "", &opts); err != nil {
		t.Fatalf("unexpected add group error: %v", err)
	}

	var out bytes.Buffer
	if err := p.WriteDoc(&out, DocFormatMarkdown, WithBuiltinTemplate(DocTemplateMarkdownCode)); err != nil {
		t.Fatalf("unexpected write doc error: %v", err)
	}

	got := out.String()
	for _, needle := range []string{
		"```text",
		defaultLongOptDelimiter + "verbose",
	} {
		if !strings.Contains(got, needle) {
			t.Fatalf("expected %q in markdown output, got:\n%s", needle, got)
		}
	}
}

func TestWriteDocCustomTemplate(t *testing.T) {
	var opts struct {
		Value string `long:"value" description:"Value"`
	}

	p := NewNamedParser("custom-doc", None)
	if _, err := p.AddGroup("Application Options", "", &opts); err != nil {
		t.Fatalf("unexpected add group error: %v", err)
	}

	var out bytes.Buffer
	err := p.WriteDoc(
		&out,
		DocFormatMarkdown,
		WithTemplateString("{{ .Doc.Name }}|{{ index .Data \"mode\" }}"),
		WithTemplateData(map[string]any{"mode": "custom"}),
	)
	if err != nil {
		t.Fatalf("unexpected write doc error: %v", err)
	}

	if got := out.String(); got != "custom-doc|custom\n" {
		t.Fatalf("unexpected custom template output: %q", got)
	}
}

func TestWriteDocTemplateHelpers(t *testing.T) {
	var opts struct {
		Flag  bool     `long:"flag" required:"true" description:"A long line that should be wrapped for helper verification"`
		List  []string `long:"list" env:"APP_LIST"`
		Value string   `long:"value"`
	}

	p := NewNamedParser("helpers-doc", None)
	if _, err := p.AddGroup("Application Options", "", &opts); err != nil {
		t.Fatalf("unexpected add group error: %v", err)
	}

	tpl := strings.Join([]string{
		"{{ $g := index .Doc.Groups 0 }}",
		"{{ $flag := index $g.Options 0 }}",
		"{{ $list := index $g.Options 1 }}",
		"{{ if isRequired $flag }}req{{ end }}",
		"|{{ if isBool $flag }}bool{{ end }}",
		"|{{ if isCollection $list }}collection{{ end }}",
		"|{{ if hasEnv $list }}env={{ $list.Env }}{{ end }}",
		"|{{ if hasDefault $list }}default{{ else }}no-default{{ end }}",
		"|{{ wrap \"a b c d e\" 3 }}",
		"|{{ indent \"x\\ny\" 2 }}",
		"|{{ markdownWrap \"a b c d e f g h i j\" 8 }}",
		"|{{ markdownWrapIndent \"a b c d e f g h i j\" 2 8 }}",
	}, "")

	var out bytes.Buffer
	if err := p.WriteDoc(&out, DocFormatMarkdown, WithTemplateString(tpl)); err != nil {
		t.Fatalf("unexpected write doc error: %v", err)
	}

	got := out.String()
	for _, needle := range []string{
		"req|bool|collection|env=APP_LIST|no-default|",
		"|a b c d e|",
		"  x\n  y",
		"|a b c d e\nf g h i j",
		"|  a b c d e\n  f g h i j",
	} {
		if !strings.Contains(got, needle) {
			t.Fatalf("expected %q in helper output, got:\n%s", needle, got)
		}
	}
}

func TestWriteDocTrimDescriptionsOption(t *testing.T) {
	var opts struct {
		Value string `long:"value" description:"  line one  \n  line two  "`
	}

	p := NewNamedParser("trim-doc", KeepDescriptionWhitespace)
	p.LongDescription = "  root line one  \n  root line two  "
	if _, err := p.AddGroup("Application Options", "", &opts); err != nil {
		t.Fatalf("unexpected add group error: %v", err)
	}

	var out bytes.Buffer
	if err := p.WriteDoc(
		&out,
		DocFormatMarkdown,
		WithTemplateString("{{ .Doc.LongDescription }}|{{ (index (index .Doc.Groups 0).Options 0).Description }}"),
		WithTrimDescriptions(true),
	); err != nil {
		t.Fatalf("unexpected write doc error: %v", err)
	}

	if got := out.String(); got != "root line one\nroot line two|line one\nline two\n" {
		t.Fatalf("unexpected trimmed description output: %q", got)
	}
}

func TestWriteDocManDefault(t *testing.T) {
	var opts struct {
		Verbose bool `short:"v" long:"verbose" description:"Enable verbose output"`
	}

	p := NewNamedParser("doc-man", None)
	p.ShortDescription = "Doc man"
	if _, err := p.AddGroup("Application Options", "", &opts); err != nil {
		t.Fatalf("unexpected add group error: %v", err)
	}

	var out bytes.Buffer
	if err := p.WriteDoc(&out, DocFormatMan); err != nil {
		t.Fatalf("unexpected write doc error: %v", err)
	}

	if got := out.String(); !strings.Contains(got, ".TH doc-man 1") {
		t.Fatalf("expected man output header, got:\n%s", got)
	}
}

func TestWriteDocManMeta(t *testing.T) {
	var opts struct {
		Verbose bool `short:"v" long:"verbose" description:"Enable verbose output"`
	}

	p := NewNamedParser("meta-man", None)
	p.ShortDescription = "Meta man test"
	p.SetManSection(8)
	p.SetVersionAuthor("Test Author <author@example.com>")
	p.SetVersionURL("https://example.com")
	p.SetVersionBugsURL("https://example.com/issues")
	p.SetSeeAlso("grep(1)", "sed(1)")
	p.SetVersionLicense("MIT")

	if _, err := p.AddGroup("Application Options", "", &opts); err != nil {
		t.Fatalf("add group: %v", err)
	}

	var out bytes.Buffer
	if err := p.WriteDoc(&out, DocFormatMan); err != nil {
		t.Fatalf("write doc: %v", err)
	}

	got := out.String()

	checks := []string{
		".TH meta-man 8",
		"AUTHOR",
		"Test Author",
		"SEE ALSO",
		"grep(1), sed(1)",
		"https://example.com",
		"BUGS",
		"https://example.com/issues",
		"LICENSE",
		"MIT",
	}
	for _, tok := range checks {
		if !strings.Contains(got, tok) {
			t.Fatalf("man meta: expected %q in output:\n%s", tok, got)
		}
	}
}

func TestWriteDocManMetaDefaultSection(t *testing.T) {
	var opts struct {
		Verbose bool `short:"v" long:"verbose" description:"Enable verbose output"`
	}

	p := NewNamedParser("meta-man-default", None)
	p.SetVersionAuthor("Author Only")

	if _, err := p.AddGroup("Application Options", "", &opts); err != nil {
		t.Fatalf("add group: %v", err)
	}

	var out bytes.Buffer
	if err := p.WriteDoc(&out, DocFormatMan); err != nil {
		t.Fatalf("write doc: %v", err)
	}

	got := out.String()
	if !strings.Contains(got, ".TH meta-man-default 1") {
		t.Fatalf("expected default section 1 when only author is set:\n%s", got)
	}
}

func TestWriteDocManMetaNoMetaDefaultSection(t *testing.T) {
	var opts struct {
		Verbose bool `short:"v" long:"verbose" description:"Enable verbose output"`
	}

	p := NewNamedParser("no-meta-man", None)
	if _, err := p.AddGroup("Application Options", "", &opts); err != nil {
		t.Fatalf("add group: %v", err)
	}

	var out bytes.Buffer
	if err := p.WriteDoc(&out, DocFormatMan); err != nil {
		t.Fatalf("write doc: %v", err)
	}

	got := out.String()
	if !strings.Contains(got, ".TH no-meta-man 1") {
		t.Fatalf("expected section 1 when no man meta set:\n%s", got)
	}
}

func TestWriteDocManMetaJSON(t *testing.T) {
	var opts struct {
		Verbose bool `short:"v" long:"verbose" description:"Enable verbose output"`
	}

	p := NewNamedParser("json-man", None)
	p.SetManSection(8)
	p.SetVersionAuthor("Test Author")
	p.SetSeeAlso("foo(1)")

	if _, err := p.AddGroup("Application Options", "", &opts); err != nil {
		t.Fatalf("add group: %v", err)
	}

	var out bytes.Buffer
	if err := p.WriteDoc(&out, DocFormatJSON); err != nil {
		t.Fatalf("write doc JSON: %v", err)
	}

	got := out.String()
	for _, tok := range []string{`"meta"`, `"section": 8`, `"author": "Test Author"`, `"see_also"`} {
		if !strings.Contains(got, tok) {
			t.Fatalf("JSON man meta: expected %q in output:\n%s", tok, got)
		}
	}
}

func TestWriteDocManMetaJSONOmitted(t *testing.T) {
	var opts struct {
		Verbose bool `short:"v" long:"verbose" description:"Enable verbose output"`
	}

	p := NewNamedParser("no-meta-json-man", None)
	if _, err := p.AddGroup("Application Options", "", &opts); err != nil {
		t.Fatalf("add group: %v", err)
	}

	var out bytes.Buffer
	if err := p.WriteDoc(&out, DocFormatJSON); err != nil {
		t.Fatalf("write doc JSON: %v", err)
	}

	if strings.Contains(out.String(), `"meta"`) {
		t.Fatalf("expected meta to be absent from JSON when no meta is set:\n%s", out.String())
	}
}

func TestWriteDocManCustomTemplate(t *testing.T) {
	var opts struct {
		Value string `long:"value" description:"Value"`
	}

	p := NewNamedParser("custom-man", None)
	if _, err := p.AddGroup("Application Options", "", &opts); err != nil {
		t.Fatalf("unexpected add group error: %v", err)
	}

	var out bytes.Buffer
	err := p.WriteDoc(
		&out,
		DocFormatMan,
		WithTemplateString("{{ .Doc.Name }}|{{ quoteMan \"a\\\\b\" }}"),
	)
	if err != nil {
		t.Fatalf("unexpected write doc error: %v", err)
	}

	if got := out.String(); got != "custom-man|a\\\\b" {
		t.Fatalf("unexpected custom man template output: %q", got)
	}
}

func TestWriteDocHTMLDefault(t *testing.T) {
	var opts struct {
		Verbose bool `short:"v" long:"verbose" description:"Enable <verbose> output"`
	}

	p := NewNamedParser("doc-html", None)
	p.ShortDescription = "Doc html"
	p.LongDescription = "Long <description>"
	if _, err := p.AddGroup("Application Options", "", &opts); err != nil {
		t.Fatalf("unexpected add group error: %v", err)
	}

	var out bytes.Buffer
	if err := p.WriteDoc(&out, DocFormatHTML); err != nil {
		t.Fatalf("unexpected write doc error: %v", err)
	}

	got := out.String()
	for _, needle := range []string{
		"<!doctype html>",
		"<h1>doc-html</h1>",
		"&lt;description&gt;",
		defaultLongOptDelimiter + "verbose",
	} {
		if !strings.Contains(got, needle) {
			t.Fatalf("expected %q in html output, got:\n%s", needle, got)
		}
	}
}

func TestWriteDocHTMLStyled(t *testing.T) {
	var opts struct {
		Verbose bool `short:"v" long:"verbose" description:"Enable <verbose> output"`
	}

	p := NewNamedParser("doc-html-styled", None)
	p.ShortDescription = "Doc html styled"
	p.LongDescription = "Long <description>"
	if _, err := p.AddGroup("Application Options", "", &opts); err != nil {
		t.Fatalf("unexpected add group error: %v", err)
	}

	var out bytes.Buffer
	if err := p.WriteDoc(&out, DocFormatHTML, WithBuiltinTemplate(DocTemplateHTMLStyled)); err != nil {
		t.Fatalf("unexpected write doc error: %v", err)
	}

	got := out.String()
	for _, needle := range []string{
		"<!doctype html>",
		"prefers-color-scheme: dark",
		"<h1>doc-html-styled</h1>",
		"&lt;description&gt;",
		defaultLongOptDelimiter + "verbose",
	} {
		if !strings.Contains(got, needle) {
			t.Fatalf("expected %q in styled html output, got:\n%s", needle, got)
		}
	}
}

func TestWriteDocHTMLCustomTemplate(t *testing.T) {
	var opts struct {
		Value string `long:"value" description:"Value"`
	}

	p := NewNamedParser("custom-html", None)
	if _, err := p.AddGroup("Application Options", "", &opts); err != nil {
		t.Fatalf("unexpected add group error: %v", err)
	}

	var out bytes.Buffer
	err := p.WriteDoc(
		&out,
		DocFormatHTML,
		WithTemplateString("{{ .Doc.Name }}|{{ quoteHTML \"a<b\" }}"),
	)
	if err != nil {
		t.Fatalf("unexpected write doc error: %v", err)
	}

	if got := out.String(); got != "custom-html|a&lt;b" {
		t.Fatalf("unexpected custom html template output: %q", got)
	}
}

func TestWriteDocErrors(t *testing.T) {
	var opts struct {
		Value string `long:"value"`
	}

	p := NewNamedParser("doc-errors", None)
	if _, err := p.AddGroup("Application Options", "", &opts); err != nil {
		t.Fatalf("unexpected add group error: %v", err)
	}

	if err := p.WriteDoc(nil, DocFormatMarkdown); err == nil {
		t.Fatalf("expected nil writer error")
	}

	var out bytes.Buffer

	if err := p.WriteDoc(&out, DocFormatMan, WithBuiltinTemplate("unknown/template")); err == nil {
		t.Fatalf("expected unknown man builtin template error")
	}

	if err := p.WriteDoc(&out, DocFormatHTML, WithBuiltinTemplate("unknown/template")); err == nil {
		t.Fatalf("expected unknown html builtin template error")
	}
}

func TestWriteDocIncludeHidden(t *testing.T) {
	var opts struct {
		Visible string `long:"visible" description:"Visible option"`
		Hidden  string `long:"hidden" description:"Hidden option" hidden:"true"`
		HCmd    struct {
			Flag string `long:"flag" description:"Hidden command flag"`
		} `command:"internal" description:"Hidden cmd" hidden:"true"`
	}

	p := NewNamedParser("hidden-doc", None)
	if _, err := p.AddGroup("Application Options", "", &opts); err != nil {
		t.Fatalf("unexpected add group error: %v", err)
	}

	var withoutHidden bytes.Buffer
	if err := p.WriteDoc(&withoutHidden, DocFormatMarkdown, WithBuiltinTemplate(DocTemplateMarkdownList)); err != nil {
		t.Fatalf("unexpected write doc error: %v", err)
	}
	if strings.Contains(withoutHidden.String(), "--hidden") || strings.Contains(withoutHidden.String(), "internal") {
		t.Fatalf("did not expect hidden entities in default output:\n%s", withoutHidden.String())
	}

	var withHidden bytes.Buffer
	if err := p.WriteDoc(
		&withHidden,
		DocFormatMarkdown,
		WithBuiltinTemplate(DocTemplateMarkdownList),
		WithIncludeHidden(true),
	); err != nil {
		t.Fatalf("unexpected write doc error: %v", err)
	}

	hiddenFlag := string(defaultLongOptDelimiter) + "hidden"
	for _, needle := range []string{hiddenFlag, "### internal"} {
		if !strings.Contains(withHidden.String(), needle) {
			t.Fatalf("expected %q in hidden-enabled output, got:\n%s", needle, withHidden.String())
		}
	}

	if strings.Contains(withHidden.String(), "*(hidden)") {
		t.Fatalf("did not expect hidden markers by default, got:\n%s", withHidden.String())
	}

	var withHiddenMarked bytes.Buffer
	if err := p.WriteDoc(
		&withHiddenMarked,
		DocFormatMarkdown,
		WithBuiltinTemplate(DocTemplateMarkdownList),
		WithIncludeHidden(true),
		WithMarkHidden(true),
	); err != nil {
		t.Fatalf("unexpected write doc error: %v", err)
	}

	if !strings.Contains(withHiddenMarked.String(), "*(hidden)") {
		t.Fatalf("expected hidden markers when enabled, got:\n%s", withHiddenMarked.String())
	}
}

func TestWriteDocTemplateHasFullTagMetadata(t *testing.T) {
	var opts struct {
		Mode string `long:"mode" description:"Mode" choice:"fast" choice:"safe" no-ini:"true" key-value-delimiter:":"`
		Cmd  struct {
			Flag bool `long:"flag" description:"Flag"`
		} `command:"run" description:"Run command" pass-after-non-option:"true" subcommands-optional:"true"`
	}

	p := NewNamedParser("meta-doc", None)
	if _, err := p.AddGroup("Application Options", "", &opts); err != nil {
		t.Fatalf("unexpected add group error: %v", err)
	}

	tpl := strings.Join([]string{
		"{{ $g := index .Doc.Groups 0 }}",
		"{{ $o := index $g.Options 0 }}",
		"choice={{ index $o.Tags \"choice\" 0 }},",
		"noini={{ index $o.Tags \"no-ini\" 0 }},",
		"kvd={{ index $o.Tags \"key-value-delimiter\" 0 }},",
		"grpns={{ $g.Namespace }},",
		"cmd={{ (index .Doc.Commands 0).Name }},",
		"pass={{ (index .Doc.Commands 0).PassAfterNonOption }},",
		"subopt={{ (index .Doc.Commands 0).SubcommandsOptional }}",
	}, "")

	var out bytes.Buffer
	if err := p.WriteDoc(&out, DocFormatMarkdown, WithTemplateString(tpl)); err != nil {
		t.Fatalf("unexpected write doc error: %v", err)
	}

	got := out.String()
	for _, needle := range []string{
		"choice=fast",
		"noini=true",
		"kvd=:",
		"cmd=run",
		"pass=true",
		"subopt=true",
	} {
		if !strings.Contains(got, needle) {
			t.Fatalf("expected %q in metadata output, got:\n%s", needle, got)
		}
	}
}

func TestWriteDocTemplateIncludesCommandGroupsAndLinearArgs(t *testing.T) {
	var opts struct {
		Positional struct {
			Input  string `positional-arg-name:"input" description:"Input file"`
			Output string `positional-arg-name:"output" description:"Output file"`
		} `positional-args:"yes"`

		Add struct{} `command:"add" command-group:"Content" description:"Add item"`

		Config struct{} `command:"config" command-group:"Administration" description:"Configure app"`
	}

	p := NewNamedParser("group-doc", None)
	if _, err := p.AddGroup("Application Options", "", &opts); err != nil {
		t.Fatalf("unexpected add group error: %v", err)
	}

	tpl := strings.Join([]string{
		"arg0={{ (index .Doc.Args 0).Name }},",
		"arg1={{ (index .Doc.Args 1).Name }},",
		"cmd-group={{ (index .Doc.CommandGroups 0).Name }}:",
		"{{ (index (index .Doc.CommandGroups 0).Commands 0).Name }}",
	}, "")

	var out bytes.Buffer
	if err := p.WriteDoc(&out, DocFormatMarkdown, WithTemplateString(tpl)); err != nil {
		t.Fatalf("unexpected write doc error: %v", err)
	}

	got := out.String()
	for _, needle := range []string{
		"arg0=input,arg1=output",
		"cmd-group=Content:add",
	} {
		if !strings.Contains(got, needle) {
			t.Fatalf("expected %q in grouped metadata output, got:\n%s", needle, got)
		}
	}
}

func TestWriteDocBuiltinTemplatesRenderCommandGroupsAndLinearArgs(t *testing.T) {
	var opts struct {
		Positional struct {
			Input string `positional-arg-name:"input" description:"Input file"`
		} `positional-args:"yes"`

		Add struct{} `command:"add" command-group:"Content" description:"Add item"`
	}

	p := NewNamedParser("group-doc", None)
	if _, err := p.AddGroup("Application Options", "", &opts); err != nil {
		t.Fatalf("unexpected add group error: %v", err)
	}

	tests := []struct {
		name     string
		format   DocFormat
		template string
		want     []string
	}{
		{
			name:     "markdown list",
			format:   DocFormatMarkdown,
			template: DocTemplateMarkdownList,
			want:     []string{"**Content**", "`input`"},
		},
		{
			name:     "markdown table",
			format:   DocFormatMarkdown,
			template: DocTemplateMarkdownTable,
			want:     []string{"**Content**", "`input`"},
		},
		{
			name:     "markdown code",
			format:   DocFormatMarkdown,
			template: DocTemplateMarkdownCode,
			want:     []string{"**Content**", "input - Input file"},
		},
		{
			name:     "html default",
			format:   DocFormatHTML,
			template: DocTemplateHTMLDefault,
			want:     []string{"<h3>Content</h3>"},
		},
		{
			name:     "html styled",
			format:   DocFormatHTML,
			template: DocTemplateHTMLStyled,
			want:     []string{"<h3>Content</h3>"},
		},
		{
			name:     "man default",
			format:   DocFormatMan,
			template: DocTemplateManDefault,
			want:     []string{"\\fBContent\\fP"},
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			var out bytes.Buffer
			if err := p.WriteDoc(&out, test.format, WithBuiltinTemplate(test.template)); err != nil {
				t.Fatalf("unexpected write doc error: %v", err)
			}
			got := out.String()
			for _, want := range test.want {
				if !strings.Contains(got, want) {
					t.Fatalf("expected %q in grouped built-in doc output, got:\n%s", want, got)
				}
			}
		})
	}
}

func TestWriteDocJSON(t *testing.T) {
	var opts struct {
		Verbose bool   `short:"v" long:"verbose" description:"Enable verbose output"`
		Output  string `long:"output" default:"stdout" description:"Output file"`
		Run     struct {
			Force bool `long:"force" description:"Force execution"`
		} `command:"run" description:"Run command" aliases:"exec"`
	}

	p := NewNamedParser("testapp", None)
	p.ShortDescription = "Test application"

	if _, err := p.AddGroup("Application Options", "", &opts); err != nil {
		t.Fatalf("AddGroup: %v", err)
	}

	var buf bytes.Buffer
	if err := p.WriteDoc(&buf, DocFormatJSON); err != nil {
		t.Fatalf("WriteDoc JSON: %v", err)
	}

	raw := buf.Bytes()
	if !json.Valid(raw) {
		t.Fatalf("output is not valid JSON: %s", raw)
	}

	var doc map[string]any
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}

	if doc["name"] != "testapp" {
		t.Errorf("name: got %v, want testapp", doc["name"])
	}
	if doc["short_description"] != "Test application" {
		t.Errorf("short_description: got %v, want 'Test application'", doc["short_description"])
	}
	if _, ok := doc["generated_at"]; ok {
		t.Error("generated_at must not appear in JSON output")
	}

	cmds, _ := doc["commands"].([]any)
	if len(cmds) == 0 {
		t.Fatal("expected at least one command in JSON")
	}
	cmd := cmds[0].(map[string]any)
	if cmd["name"] != "run" {
		t.Errorf("command name: got %v, want run", cmd["name"])
	}
	aliases, _ := cmd["aliases"].([]any)
	if len(aliases) == 0 || aliases[0] != "exec" {
		t.Errorf("command aliases: got %v, want [exec]", aliases)
	}

	groups, _ := doc["groups"].([]any)
	if len(groups) == 0 {
		t.Fatal("expected at least one group in JSON")
	}
	options, _ := groups[0].(map[string]any)["options"].([]any)
	longNames := make([]string, 0, len(options))
	for _, o := range options {
		if ln, ok := o.(map[string]any)["long"].(string); ok {
			longNames = append(longNames, ln)
		}
	}
	for _, want := range []string{"verbose", "output"} {
		found := false
		for _, ln := range longNames {
			if ln == want {
				found = true
				break
			}
		}
		if !found {
			t.Errorf("option %q not found in JSON groups; got %v", want, longNames)
		}
	}
}

func TestWriteDocJSONSecretMasked(t *testing.T) {
	var opts struct {
		Token  string `long:"token" default:"secret123" secret:"true" description:"API token"`
		Region string `long:"region" choices:"us;eu" secret:"true" description:"Region"`
	}

	p := NewNamedParser("secapp", None)
	if _, err := p.AddGroup("Options", "", &opts); err != nil {
		t.Fatalf("AddGroup: %v", err)
	}

	var buf bytes.Buffer
	if err := p.WriteDoc(&buf, DocFormatJSON); err != nil {
		t.Fatalf("WriteDoc JSON: %v", err)
	}

	out := buf.String()

	if strings.Contains(out, "secret123") {
		t.Error("secret default value 'secret123' must not appear in JSON output")
	}
	if strings.Contains(out, `"us"`) || strings.Contains(out, `"eu"`) {
		t.Error("choices for secret option must not appear in JSON output")
	}
	if !strings.Contains(out, `"secret": true`) {
		t.Error("'secret: true' marker must be present in JSON output")
	}
	if !strings.Contains(out, secretValueMask) {
		t.Error("secret mask sentinel must appear in JSON output for masked default")
	}
}

func TestWriteDocJSONDocOptions(t *testing.T) {
	var opts struct {
		Name   string `long:"name" description:"Name"`
		Hidden string `long:"secret-key" hidden:"true" description:"Hidden key"`
	}

	p := NewNamedParser("optapp", None)
	if _, err := p.AddGroup("Options", "", &opts); err != nil {
		t.Fatalf("AddGroup: %v", err)
	}

	var buf bytes.Buffer
	if err := p.WriteDoc(&buf, DocFormatJSON); err != nil {
		t.Fatalf("WriteDoc: %v", err)
	}
	if strings.Contains(buf.String(), "secret-key") {
		t.Error("hidden option must not appear without WithIncludeHidden")
	}

	buf.Reset()
	if err := p.WriteDoc(&buf, DocFormatJSON, WithIncludeHidden(true)); err != nil {
		t.Fatalf("WriteDoc with hidden: %v", err)
	}
	if !strings.Contains(buf.String(), "secret-key") {
		t.Error("hidden option must appear with WithIncludeHidden(true)")
	}
}
