.TH golden-doc 1 "14 November 2023"
.SH NAME
golden-doc \- Golden doc parser
.SH SYNOPSIS
\fBgolden-doc\fP [OPTIONS]
.SH DESCRIPTION
Long description for golden tests.
Includes options, groups and commands.
.SH OPTIONS
.SS Application Options
Main options
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Enable verbose output
.TP
\fB\-\-config\fR <default: \fIconfig.yaml\fR> (\fIrequired\fR)
Path to config
\fBEnvironment\fP: MY_APP_APP_CONFIG
.TP
\fB\-\-mode\fR <default: \fIfast\fR>
Execution mode
\fBChoices\fP: fast, safe
.TP
\fB\-\-tag\fR <default: \fIapi\fR>
Tag filter
.TP
\fB\-\-header\fR <default: \fIx-env:dev\fR>
HTTP headers
\fBdelimiter\fP: :
.TP
\fB\-\-level\fR [\fI=info\fR]
Log level
\fBOptional value\fP: info
.SS Database Options
.TP
\fB\-\-db.host\fR <default: \fI127.0.0.1\fR>
Database host
\fBEnvironment\fP: MY_APP_DB_HOST
.TP
\fB\-\-db.port\fR <default: \fI5432\fR>
Database port
\fBEnvironment\fP: MY_APP_DB_PORT
.SH ARGUMENTS
.TP
\fBinput\fP
Input resource
.SH COMMANDS
.SS run
Run command
.PP
Execute deployment workflow.
.PP
\fBUsage\fP: golden-doc [OPTIONS] run [run-OPTIONS]
.SS Run command
Execute deployment workflow.
.TP
\fB\-\-force\fR
Force execution
.TP
\fB\-\-plan\fR
Show execution plan only
.SS Arguments
.TP
\fBtarget\fP
Deployment target

.SS status
Show status
.PP
Read and print current status.
.PP
\fBUsage\fP: golden-doc [OPTIONS] status [status-OPTIONS]
.SS Show status
Read and print current status.
.TP
\fB\-\-json\fR
JSON output
